### ISSUE TITLE
Default install scenario doesn't work with Angular 10: Doesn't find types in ng-gapi but in ng-gapi/lib/src

### ISSUE THREAD

**Issue by Kungitoo** [rubenCodeforges/ng-gapi#103]
```
import { NgModule } from '@angular/core';

import {
  GoogleApiModule, 
  GoogleApiService, 
  GoogleAuthService, 
  NgGapiClientConfig, 
  NG_GAPI_CONFIG,
  GoogleApiConfig
} from "ng-gapi/lib/src";

```

So I've done a fresh install of angular CLI, ng new project, npm i ng-gapi and when I try to import the types it doesn't see them

![image](https://user-images.githubusercontent.com/6378638/88807115-90fae600-d1b1-11ea-95da-f966daa9f5dc.png)

Only when I do `} from "ng-gapi/lib/src";` does it find the types

My deps:

  "dependencies": {
    "@angular/animations": "~10.0.5",
    "@angular/cdk": "^10.1.1",
    "@angular/common": "~10.0.5",
    "@angular/compiler": "~10.0.5",
    "@angular/core": "~10.0.5",
    "@angular/forms": "~10.0.5",
    "@angular/material": "^10.1.1",
    "@angular/platform-browser": "~10.0.5",
    "@angular/platform-browser-dynamic": "~10.0.5",
    "@angular/router": "~10.0.5",
    "component": "^1.1.0",
    "ng-gapi": "0.0.93",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },

EDIT: Ok, I guess the export thing I'm doing maybe doesn't make sense. I tried doing the same thing as for Angular Material where I create a separate module for setting it up but whatever. What still doesn't work is the types

**Comment by rubenCodeforges** [comment]
Fixed in latest release
