### ISSUE TITLE
Does this support Google Drive API integration?

### ISSUE THREAD

**Issue by Kungitoo** [rubenCodeforges/ng-gapi#104]
I'm desparately tring to get my simple Angular app to use Google Drive app storage. I'm trying to first try and get this basic scenario working https://developers.google.com/drive/api/v3/quickstart/js . Is this library supposed to provide the types for this scenario?

**Comment by rubenCodeforges** [comment]
It should

**Comment by Kungitoo** [comment]
![image](https://user-images.githubusercontent.com/6378638/88809741-bccb9b00-d1b4-11ea-8f4e-a47b2fb32471.png)
where is this type supposed to be?

**Comment by rubenCodeforges** [comment]
your code does not tell much , it looks more like js code , are you sure you are using Angular ?

**Comment by Kungitoo** [comment]
I've copied the example code from the quickstart I linked which is the official Google quickstart for the Drive API and I'm trying to get this example to work in my sample Angular app. Also, the stackblitz example which you have linked in the readme has errors in it which I guess is not a good thing https://stackblitz.com/edit/ng-gapi-example?file=app%2FUserService.ts and it's on a 0.0.45 version while the on I get from npm is 0.0.93 which sounds pretty far apart

**Comment by rubenCodeforges** [comment]
> I've copied the example code from the quickstart I linked which is the official Google quickstart for the Drive API and I'm trying to get this example to work in my sample Angular app. Also, the stackblitz example which you have linked in the readme has errors in it which I guess is not a good thing https://stackblitz.com/edit/ng-gapi-example?file=app%2FUserService.ts and it's on a 0.0.45 version while the on I get from npm is 0.0.93 which sounds pretty far apart

PRs to update the demo are welcomed, this is a open source project , feel free to contribute.
