### ISSUE TITLE
cross-site resource warning

### ISSUE THREAD

**Issue by malizia-g** [rubenCodeforges/ng-gapi#106]
Hello,
I created a basic project to test the Plugin.
Every time I start the project on Chrome I get this warning: 

> A cookie associated with a cross-site resource at http://google.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

 Has anybody solved the problem without disable the warning on Chrome settings?

Thanks for your work

**Comment by rubenCodeforges** [comment]
This does not seems to be related to ng-gapi , its more like a CORS issue
