### ISSUE TITLE
Consent Screen / Verification

### ISSUE THREAD

**Issue by bendg25** [rubenCodeforges/ng-gapi#110]
Hi, so we have had our verification rejected, because they cannot see the client id in the URL bar for the consent screen.
Is it possible to do a release where client id is the first parameter?

"Enlarge the OAuth Consent Screen to show the URL including the Client ID (This is not required for native Android and iOS apps)."

**Comment by rubenCodeforges** [comment]
Hi , i dont understand how it relates to the lib ?

**Comment by bendg25** [comment]
I suppose we need a way of controlling modal size, but maybe this is baked into oauth-gapi lib?

**Comment by rubenCodeforges** [comment]
@bendg25 dont think it relates to `ng-gapi` but maybe to the core `gapi` lib. 
so i can just suggest you look in to the `gapi` docs or try searching for `gapi window size` or something like that.

**Comment by bendg25** [comment]
![Client_id (2)](https://user-images.githubusercontent.com/4302429/110237730-6c2fd380-7f35-11eb-8a86-b75e133fd527.png)

This is what they are after

**Comment by rubenCodeforges** [comment]
well this is not controlled by ng-gapi , as i mentioned previously, please
take a look at gapi docs

**Comment by bendg25** [comment]
Yes I do get that :) Just sharing FYI.  Kind of annoying as I assume gapi is maintained by Google right?

**Comment by rubenCodeforges** [comment]
yes you are right, gapi - google api

**Comment by bendg25** [comment]
They have verified it anyway, once the above ^^ was explained.
