### ISSUE TITLE
Additions and Enhancements 

### ISSUE THREAD

**Issue by rubenCodeforges** [rubenCodeforges/ng-gapi#18]
### Hello guys , first for all thanks for using the lib and supporting me by staring it.

With that issue i would like to gather some proposals for addition and enhancements for that lib.
Please fill free to comment here what you would like to see in the lib.
Thanks.

**Comment by topikus** [comment]
It would be good to see your lib supporting ssr (angular universal). :)
Now it use ref to document object explicitly.

**Comment by rubenCodeforges** [comment]
@topikus are there any issues now ?

**Comment by topikus** [comment]
`ReferenceError: document is not defined
          at Observable._subscribe (/home/local/www/new.cp.linksmanagement.com-frontend/dist/server.js:46511:33)
          at Observable._trySubscribe (/home/local/www/new.cp.linksmanagement.com-frontend/dist/server.js:241:25)
          at Observable.subscribe (/home/local/www/new.cp.linksmanagement.com-frontend/dist/server.js:229:65)
          at new GoogleApiService (/home/local/www/new.cp.linksmanagement.com-frontend/dist/server.js:46500:25)
`
You use document at 
` private loadGapi(): Observable<void> {
        return Observable.create((observer: Observer<boolean>) => {
            let node = document.createElement('script');
            node.src = this.gapiUrl;
            node.type = 'text/javascript';
            node.charset = 'utf-8';
            document.getElementsByTagName('head')[0].appendChild(node);
            node.onload = () => {
                observer.next(true);
                observer.complete();
            };
        });
    }`

**Comment by rubenCodeforges** [comment]
@topikus ahh right , well it is required to load the lib gapi.js. i could include it as a file but then it will freeze the version of gapi

**Comment by topikus** [comment]
Maybe, you can use something like this
`import { PLATFORM_ID } from '@angular/core';
 import { isPlatformBrowser, isPlatformServer } from '@angular/common';
 
 constructor(@Inject(PLATFORM_ID) private platformId: Object) { ... }
 
 ngOnInit() {
   if (isPlatformBrowser(this.platformId)) {
      // Client only code.
      ...
   }`

**Comment by Khawaga** [comment]
Any updates on Universal support?

**Comment by rubenCodeforges** [comment]
@Khawaga My next goal is to update the lib to use Angular 5 as well as some refactoring.
Unfortunate Universal support is not on top priority now
