### ISSUE TITLE
How do we use this module?

### ISSUE THREAD

**Issue by ndunas** [rubenCodeforges/ng-gapi#22]
As I see there used to be an example file which has been removed due to breaking changes.

The only hint we get right now is: 

> // Here we can use gapi

any further instructions on how we could actually use it?

**Comment by rubenCodeforges** [comment]
@ndunas this module is sort of a wrapper for gapi , that allows you to integrate it in to angular project.

here is a small example https://github.com/rubenCodeforges/iService/blob/feature/users/src/app/common/navbar/NavbarComponent.ts#L19

after subscribing youll work with the gapi.auth , if you need more information for gapi , refer to the google docs for it https://developers.google.com/api-client-library/javascript/reference/referencedocs

**Comment by ndunas** [comment]
Thank you very much @rubenCodeforges !

**Comment by ndunas** [comment]
@rubenCodeforges The small example page is not working anymore

**Comment by rubenCodeforges** [comment]
@ndunas yes because ive merged the feature branch in to master 
here is the link from master https://github.com/rubenCodeforges/iService/blob/development/src/app/common/navbar/NavbarComponent.ts

**Comment by Garric15** [comment]
Do you have some exemples on how we can use gapi other than authentication, like calling the drive api ?
Also, do you have exemples on how to use gapi beside the `onLoad()` method ? Like calling the FooService anytime.

**Comment by rubenCodeforges** [comment]
@Garric15 Hi.
Beside on load see the example ive shared with @ndunas https://github.com/rubenCodeforges/iService/blob/development/src/app/common/navbar/NavbarComponent.ts
here the `this.googleAuth.getAuth()` is used like a normal service.

To use the drive api , the easiest way is to use the authToken from gapi.auth , which you get when you use the `authService` in ng-gapi. Then you simply use the api https://developers.google.com/drive/v3/reference/files/list

**Comment by Garric15** [comment]
Is this possible to use the gapi like [this exemple](https://developers.google.com/drive/v3/web/quickstart/js) ?

**Comment by rubenCodeforges** [comment]
@Garric15 yes but use the loader:
```
 gapiService.onLoad().subscribe(()=> {
           // Here we can use gapi
            gapi.whatever
        });
```
