### ISSUE TITLE
Feature: change platform.js to api.js

### ISSUE THREAD

**Issue by aaaaahaaaaa** [rubenCodeforges/ng-gapi#24]
Hi. Why are you [using](https://github.com/rubenCodeforges/ng-gapi/blob/master/src/GoogleApiService.ts#L11) the `platform.js` library (`apis.google.com/js/platform.js`) instead of `api.js` (`apis.google.com/js/api.js`)? Correct me if i'm wrong but `platform.js` is for the Google+ JavaScript API, no?

**Comment by rubenCodeforges** [comment]
Good catch , i guess the docs got updated , because earlier they had platform.js

**Comment by rubenCodeforges** [comment]
@aaaaahaaaaa please check out this pr https://github.com/rubenCodeforges/ng-gapi/pull/25 
i would appreciate much if you can try it out

**Comment by aaaaahaaaaa** [comment]
Checking out the PR right now. I have the following error **at runtime** when referencing my local version of `ng-gapi`: 
>Can't resolve all parameters for GoogleApiService

My `app.module.ts` looks like this:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { GoogleApiModule, NG_GAPI_CONFIG, NgGapiClientConfig } from 'path/to/ng-gapi/lib';

let gapiConfig: NgGapiClientConfig = {
	....
}

@NgModule({
	declarations: [
		AppComponent,
	],
	imports: [
		BrowserModule,
		GoogleApiModule.forRoot({
            provide: NG_GAPI_CONFIG,
            useValue: gapiConfig
        })
	],
	providers: [],
	bootstrap: [AppComponent]
})
export class AppModule { }
```

I can't seem to find the source of the problem. Any idea?

**Comment by rubenCodeforges** [comment]
`import { GoogleApiModule, NG_GAPI_CONFIG, NgGapiClientConfig } from 'path/to/ng-gapi/lib';`

this import looks not correct to me

**Comment by aaaaahaaaaa** [comment]
How do you import your local version of the module?

**Comment by aaaaahaaaaa** [comment]
Bare with me, this is the first time I'm actually trying to import a module located in an external folder to an ng-cli project.

**Comment by aaaaahaaaaa** [comment]
I also just tried to add the path in the `tsconfig.json` file:
```
...
"paths": {
   "ng-gapi": ["path/to/ng-gapi/lib"]
}
```
But then i have the following error when compiling the project:
>ERROR in Error: Error encountered resolving symbol values statically. Calling function 'GoogleApiModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in...

**Comment by rubenCodeforges** [comment]
i dont import manually , i have intellij doing the dirty job and i recommend you to use a good IDE that can make the imports for you.
but nevermind , ill deploy tomorrow a new version with this changes

**Comment by aaaaahaaaaa** [comment]
Well I'm still curious to know what's the proper way to import an external module. I actually still haven't found the right answer online. Are you using VSC? But it's weird coz I don't think your IDE is doing anything fancy when importing a module automatically. Does it update your tsconfig.json?

**Comment by aaaaahaaaaa** [comment]
Anyway, I agree it's not related to the current issue.

**Comment by rubenCodeforges** [comment]
@aaaaahaaaaa well in case of the source of that library, you put the source files inside you cli project.

lets say under app/ng-gapi

then you simply import the Module insider your AppModule ( not d.ts files )
And everything should be going.

**Comment by rubenCodeforges** [comment]
Changes deployed
