### ISSUE TITLE
GoogleUser reference?

### ISSUE THREAD

**Issue by stephencawood** [rubenCodeforges/ng-gapi#28]
In your GoogleAuthService example, where are you getting the Interface for GoogleUser?

Thanks

**Comment by rubenCodeforges** [comment]
Hi , from typings, see the package json:
```json
  "dependencies": {
    "@types/gapi": "^0.0.35",
    "@types/gapi.auth2": "^0.0.44"
  },
```

**Comment by stephencawood** [comment]
Thanks for the message, I have those in there and I still get this:
error TS2304: Cannot find name 'GoogleUser'.

Is there an import statement required? I'll try rebuilding my modules.

**Comment by rubenCodeforges** [comment]
@stephencawood sure you need to import it , your IDE should it for you.
I never import by hand.

**Comment by stephencawood** [comment]
Thanks. I'm using VS Code. I don't know why, but I had to reference it like this. Looks like a tsconfig issue, but I can't see the problem.

private user: gapi.auth2.GoogleUser;

**Comment by KlwntSingh** [comment]
@stephencawood , You can provide the reference to GoogleUser object the way @rubenCodeforges did in his example.
Just import gapi.auth2.GoogleUser and assign it to GoogleUser in service.ts like this
`import  GoogleUser = gapi.auth2.GoogleUser;` 

Refer the attached screenshot.
![screenshot from 2017-11-25 20-28-44](https://user-images.githubusercontent.com/10296556/33236086-60c3dcb0-d21f-11e7-9f0b-67c264a9fe0d.png)

Hope It helps!

**Comment by stephencawood** [comment]
thanks @KlwntSingh. looks good

**Comment by rubenCodeforges** [comment]
@KlwntSingh  thanks for help :+1:
