### ISSUE TITLE
Not working with SystemJS 

### ISSUE THREAD

**Issue by holtzilya2008** [rubenCodeforges/ng-gapi#29]
When using in a project with SystemJS got the following error:

> Error: Unable to dynamically transpile ES module
>   A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`.
>  Instantiating http://localhost:3010/node_modules/ng-gapi/lib/index.js
>  Loading http://localhost:3010/app/app.module.js
>  Loading app
>    at transpile (instantiate.js:467)
>    at instantiate.js:245
>    at ZoneDelegate.invoke (zone.js:392)
>    at Zone.run (zone.js:142)
>    at zone.js:873
>    at ZoneDelegate.invokeTask (zone.js:425)
>    at Zone.runTask (zone.js:192)
>    at drainMicroTaskQueue (zone.js:602)
>    at <anonymous>
> 

**The parts of systemjs.config.ts**

> map : {
>  ... 
> 'ng-gapi': 'node_modules/ng-gapi/lib'
> }
> 
> packages: {
> ...
>             'ng-gapi': {
>                 main: 'index.js',
>                 defaultExtension: 'js'
>             } 

**app.module** 
> ...
> import { GoogleApiModule, NG_GAPI_CONFIG } from 'ng-gapi';
> ...
> export interface NgGapiClientConfig extends ClientConfig {
>     discoveryDocs: string[];
>   }
> ...
> 
> @NgModule({
>     imports: [
> ...
> GoogleApiModule.forRoot({
>             provide: NG_GAPI_CONFIG,
>             useValue: gapiClientConfig
>           }),
> ...

**Comment by rubenCodeforges** [comment]
@holtzilya2008 Im so sorry , but im not supporting SystemJs.

**Comment by rubenCodeforges** [comment]
@holtzilya2008 я закрою тогда , если нужна помощь можеш в скайп писать eldar2ndpara но как я уже сказал SystemJs не потдерживаю , темка устарела малеха.
