### ISSUE TITLE
Can I use multiple instances of gapi.client in the same time ?

### ISSUE THREAD

**Issue by sahlouls** [rubenCodeforges/ng-gapi#31]

**Comment by rubenCodeforges** [comment]
as far as i know there is only one gapi provided by google if you try to load it twice it will overide itself.
so in general you cant and im guess you should not even try it.

**Comment by sahlouls** [comment]
yes, there is only one gapi but it is possible to have multiple clients. For example: a web application that will need to use custom endpoints + public apis then there is the need to have multiple clients one for each.

**Comment by rubenCodeforges** [comment]
@sahlouls can you give an example on how you want to use gapi ?
I just dont get what you want to achieve.
are you trying to have 2 instances of gapi.client or are you trying to include 2 gapi libraries ?

**Comment by sahlouls** [comment]
I have an application running on appengine. I use cloud endpoints so I need a gapi client (1st client). In the same time I need to interact with other services (Google+, Drive, etc ) and for theses I need also other gapi clients.
Yes: How can I have multiple instances with differents configuration of gapi.client ?

**Comment by rubenCodeforges** [comment]
Ok i got it.
So in general ng-gapi is injecting the gapi lib in to the dom and fires `next()` when its loaded (Observable)
this is done in https://github.com/rubenCodeforges/ng-gapi/blob/master/src/GoogleApiService.ts

As you can see the configs are just saved here , they are not used in this service.
Now if you take a look at https://github.com/rubenCodeforges/ng-gapi/blob/master/src/GoogleAuthService.ts#L28 here is where the config is used.

Let assume you have a default config which is used for the ng-gapi authService.
What you can now do is create a similar class : 
```Typescript
@Injectable()
export class GoogleAuthService {
    private MyNewGoogleServiceOrClientOrWhatever: any = undefined;

    constructor(private googleApi: GoogleApiService) {
        this.googleApi.onLoad().subscribe(() => {
            // Reference https://developers.google.com/api-client-library/javascript/reference/referencedocs
            gapi.load('client:auth2', () => {
                let newConfigs: NgGapiClientConfig = {
                    client_id: "CLIENT_ID",
                    discoveryDocs: ["https://analyticsreporting.googleapis.com/$discovery/rest?version=v4"],
                    scope: [
                        "https://www.googleapis.com/auth/analytics.readonly",
                        "https://www.googleapis.com/auth/analytics"
                    ].join(" ")
                };
                let newService = gapi.whateverServiceYouWant.init(newConfigs);
                this.MyNewGoogleServiceOrClientOrWhatever = newService;
            });
        };
    }
}
```
This is just a rough example , but you should get the idea.

In general ng-gapi gives you the possibility to use gapi as Angular service and access it via observable

**Comment by sahlouls** [comment]
Hi Ruben,

Thanks for the reply, I will give it a try and let you know.

**Comment by rubenCodeforges** [comment]
you are welcome , if it worked for you just close the issue
