### ISSUE TITLE
Retrieve CurrentUser after refresh of the browser

### ISSUE THREAD

**Issue by KevinBouchere** [rubenCodeforges/ng-gapi#33]
Hello,

I would like to know how can I restore the GoogleUser after a refresh of the page?
I still have the token in the session but the GoogleUser is set as Undefine after "F5"
Is there a method to call the GAPI to retrieve the currentUser session? 

Thanks.

**Comment by rubenCodeforges** [comment]
I would recommend to you check out the google api docs for that https://developers.google.com/api-client-library/javascript/reference/referencedocs

**Comment by rubenCodeforges** [comment]
And to check authentication on page load ( before component get displayed )
You can use: 
1. Router Guard - https://angular.io/guide/router#guards
2. Resolver - https://angular.io/guide/router#resolve-guard

**Comment by KevinBouchere** [comment]
Thanks for your anwser.
I found the solution by calling again the google GetAuth

```
this.googleAuthService.getAuth()
        .subscribe((auth) => {
            this.setUser(auth.currentUser.get()); ;
        });
```

**Comment by rubenCodeforges** [comment]
@KevinBouchere yep thats the right way
