### ISSUE TITLE
How do we call a google API (like Calendar API) 

### ISSUE THREAD

**Issue by KevinBouchere** [rubenCodeforges/ng-gapi#36]
Hi Ruben,

I'm a bit lost, I don't find the correct way to call an API like the Google Calendar API.

Do you have an exemple of implementation of the class bellow with gapi object ? 

I know that I have to initialize the apiKey, do I need to use the gapi.client.init ? 

```
export class FooService {
    constructor(gapiService: GoogleApiService) {
        gapiService.onLoad().subscribe(()=> {
           // Here we can use gapi
           // Do I need to use the gapi.client.init ? 
           // 
        });
    }
}
```
thanks 

Kévin

**Comment by KevinBouchere** [comment]
When I trie to use gapi.client.init 

`  public testKevin(): void {
    this.gapiService.onLoad().subscribe(()=> {
        // Here we can use gapi
               
        gapi.client.init({
            apiKey:'MyAPIKEY',
            discoveryDocs:['https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest'],
            clientId:'ID.apps.googleusercontent.com',
            scope:'https://www.googleapis.com/auth/calendar',
            hosted_domain:''
           }
        ).then(function () {
            gapi.client.load('calendar', 'v3');   
                    let req = gapi.client.calendar.events.list({
                    calendarId: 'primary',
                maxResult: 10
                    });
        }); 
    });
  }`

 I get this error.

![capture d ecran 2017-12-10 a 12 23 29](https://user-images.githubusercontent.com/33981433/33804434-1f5efdcc-dda5-11e7-8e44-b673bec13b22.png)

**Comment by rubenCodeforges** [comment]
@KevinBouchere hi , ive a a example project that uses the tasks api `https://github.com/rubenCodeforges/ng-gapi/tree/feature/example-project/examples/src`

In general all what you need from gapi is to get `authToken` , then you use it fro any API.
Here for example a GET endpoint for calendar list `https://developers.google.com/google-apps/calendar/v3/reference/calendarList/get` you see on the right side what fields it requires.

**Comment by rubenCodeforges** [comment]
And a answer to your second comment : 
```typeScript
gapi.client.init({
            apiKey:'MyAPIKEY',
            discoveryDocs:['https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest'],
            clientId:'ID.apps.googleusercontent.com',
            scope:'https://www.googleapis.com/auth/calendar',
            hosted_domain:''
           }
        )
```
This is not required , as `ng-gapi` is doing it for you when you provide configuration as described in the docs

**Comment by AndyBrownlie** [comment]
Ruben

I tried to find the example you are referring to with tasks. I can only find REST calls via httpService, rather than use of the gapi.  
I think what Kevin is looking for (as am I) are examples of use of gapi, e.g. gapi.client.request.  
Are we missing something?  I thought the whole point of your library was to enable use of gapi?

(Note, I am getting the same undefined error with gapi.client as Kevin. _

thanks in advance
regards
Andy

**Comment by rubenCodeforges** [comment]
this is gapi https://developers.google.com/api-client-library/javascript/reference/referencedocs my lib wraps it for you to use in Angular.

**Comment by rubenCodeforges** [comment]
@AndyBrownlie the undefined error , have you provided the configs in the AppModule or did you do it like Kevin ?

**Comment by mfgea** [comment]
@rubenCodeforges I coudn't do it using the docs, seems like the 'client' api is not loaded anywhere. Searched through the code for some clues and could not think of any way to solve it.

@AndyBrownlie @KevinBouchere I got it working with this code:

```
  constructor(
    private gapiService: GoogleApiService,
    private zone: NgZone
  ) {
    gapiService.onLoad().subscribe(() => {
      gapi.load('client', () => {
        gapi.client
          .load("https://sheets.googleapis.com/$discovery/rest?version=v4", "1")
          .then(this.getData.bind(this));
      });
    });
  }
```

That's the constructor of my data service. I also had to add ngZone to sync the calls from gapi to the Angular lifecycle.

**Comment by rubenCodeforges** [comment]
yes thats a good way to go
