### ISSUE TITLE
Support for authorization flow

### ISSUE THREAD

**Issue by muliyul** [rubenCodeforges/ng-gapi#37]
Just a feature request :>

The flow is described [here](https://developers.google.com/identity/sign-in/web/reference#advanced) in the _advanced_ section.

**Comment by rubenCodeforges** [comment]
@muliyul the warning in the docs are pointing out that this approach is not recommended

**Comment by muliyul** [comment]
My case do apply here:

> Your application has its own session management infrastructure, and it only requires the ID Token once to identify the user in your backend.

**Comment by rubenCodeforges** [comment]
you could do it for example like: 
```TypeScript

constructor(gapiService: GoogleApiService) {
        gapiService.onLoad().subscribe(()=> {
           gapi.auth2.authorize({ ... });
    }
```

Does this works for you ?

**Comment by muliyul** [comment]
I could do that but I like typescript better :) I guess that's a no then?

**Comment by rubenCodeforges** [comment]
it is but typescript :)
I guess you want to use authorize with Observable:
```
gapi.auth2.authorize({}).subscribe() 
```
Right ?

**Comment by muliyul** [comment]
Mhm. I guess I can transform it by myself too.

**Comment by rubenCodeforges** [comment]
yeh not very hard, but good catch , ill think about it
