### ISSUE TITLE
Insufficient Documentation

### ISSUE THREAD

**Issue by DaveOdden** [rubenCodeforges/ng-gapi#39]
Hey there. I am looking to use this wrapper for my project. The documentation does not sufficiently describe how to use ng-gapi. there's also mention of examples which would be invaluable. Will you please update the README with comprehensive instructions?

**Comment by rubenCodeforges** [comment]
What exactly is not clear ?

**Comment by JSilva94** [comment]
how do we include our apikey?

**Comment by rubenCodeforges** [comment]
@JSilva94 You probably mean CLIENT_ID
```
let gapiClientConfig: NgGapiClientConfig = {
    client_id: "CLIENT_ID",
    discoveryDocs: ["https://analyticsreporting.googleapis.com/$discovery/rest?version=v4"],
    scope: [
        "https://www.googleapis.com/auth/analytics.readonly",
        "https://www.googleapis.com/auth/analytics"
    ].join(" ")
};

@NgModule({
    imports: [
        //...
          GoogleApiModule.forRoot({
            provide: NG_GAPI_CONFIG,
            useValue: gapiClientConfig
          }),
        //...
    ]
})
export MyModule {}
```

**Comment by DaveOdden** [comment]
I tried cloning the example project under the other branch and got a bootstrap related webpack failure. Does the example work?

![screen shot 2018-03-19 at 10 41 24 am](https://user-images.githubusercontent.com/1531401/37602179-3ac917ea-2b62-11e8-8dbe-0f7b8398a2c9.png)

**Comment by rubenCodeforges** [comment]
@DaveOdden thats possible the example projects is outdated , but still it should give a overview.
can you tell what you are trying to do ?

**Comment by DaveOdden** [comment]
I am really just trying to get some Google Sheets data :/

**Comment by rubenCodeforges** [comment]
@DaveOdden here ive made a demo for you https://ng-gapi-example.stackblitz.io

**Comment by DaveOdden** [comment]
nice. I used https://stackblitz.com/edit/ng-gapi-example to see the code
