### ISSUE TITLE
gapi.client doesn't exist  

### ISSUE THREAD

**Issue by vitto-moz** [rubenCodeforges/ng-gapi#41]
I've provide confing below 
```Typescript
let gapiClientConfig: NgGapiClientConfig = {
  client_id: "******",
  discoveryDocs: ["https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest"],
  scope: [
    "https://www.googleapis.com/auth/calendar"
  ].join(" ")
};
```
authorization works, then I need to use gapi.client.calendar , but .client doesn't exist 
gapiService.onLoad().subscribe(() => {
 // try achive gapi.client here
})

One more question - do we need provide API_key? I don't see any mention of this in library's documentaion, but this requirement exist in google calendar doc example

**Comment by vitto-moz** [comment]
it seems I should use something like that
gapi.load('client:auth2', this.initClient.bind(this));
to achive client

**Comment by rubenCodeforges** [comment]
@vitto-moz you can use the `GoogleAuthService` in ng-gapi, for auth , see this example https://github.com/rubenCodeforges/ng-gapi#googleauthservice

**Comment by vitto-moz** [comment]
Thank you! I realized that I should use 
gapi.load('client:auth2', this.initClient.bind(this));

then you can achieve gapi.client.init in initClient method

**Comment by rubenCodeforges** [comment]
@vitto-moz looks like its what AuthService is doing , see this https://github.com/rubenCodeforges/ng-gapi/blob/master/src/GoogleAuthService.ts#L19

**Comment by vitto-moz** [comment]
maybe the reason it was not working for me, because there API key absent as a needed prop of config - so I could not achieve properties of gapi  I need

**Comment by vitto-moz** [comment]
Do we have a place to set API key?

**Comment by rubenCodeforges** [comment]
@vitto-moz https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiclientsetapikeyapikey
