### ISSUE TITLE
Need sample code for how to grantOfflineAccess

### ISSUE THREAD

**Issue by moasakthi** [rubenCodeforges/ng-gapi#45]
Hi @rubenCodeforges ,

First of thank you for the awesome library. 

I need to sync google calendar offline without logging in every time. For that i used, `grantOfflineAccess()` method. It responded `code="some string"`  . with that how to get calendar list.

Can you please help me out in this. i am very newbie.

**Comment by rubenCodeforges** [comment]
@moasakthi thanks for asking , this is a good one.
Im not sure if you can access calendar in offline.

gapi itself is a Client Library , see what it has to offer in the official docs https://developers.google.com/api-client-library/javascript/reference/referencedocs

And google calendar has its own api https://developers.google.com/calendar/v3/reference/

From what i can recommend without deep research , is load calendar data , store them in on of the local storages and work with that , also youll probably want a sync method , that will sync the new data with calendar data , once you have connection.

**Comment by moasakthi** [comment]
Ok @rubenCodeforges  thanks for the suggestion. i will look into it.  Is there any way to get refresh token to sync data. instead of every time i signed in. 
`auth.signIn({prompt: 'consent'}).then(res => this.signInSuccessHandler(res), err => this.signInErrorHandler(err));` but it returns only accessToken not refreshToken.

Can you please help me out to get refresh token ? and how to use refresh token once auth token expired.

**Comment by rubenCodeforges** [comment]
@moasakthi ive made a demo , maybe this will give you some hints https://ng-gapi-example.stackblitz.io

**Comment by rubenCodeforges** [comment]
and about refresh token , ill make an example a bit later

**Comment by rubenCodeforges** [comment]
@moasakthi here is a HttpInterceptor example , im using this class in one of my projects , to intercept 401 -> refreshToken and retry request

```Typescript
@Injectable()
export class HttpInterceptor implements HttpInterceptor {
    private authService: AuthService;
    private httpClient: HttpClient;

    constructor(private injector: Injector) {
    }

    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        this.authService = this.injector.get(AuthService);
        this.httpClient = this.injector.get(HttpClient);

        let authorizedRequest: HttpRequest<any> = this.getAuthorizedRequest(req);
        return next.handle(authorizedRequest)
            .do(null, (err: any) => this.handleError(err, req));
    }

    private handleError(err: any, request: HttpRequest<any>) {
        if (err instanceof HttpErrorResponse) {
            this.handleAuthError(err, request);
            throw new Error(err.message);
        }
    }

    private handleAuthError(err: HttpErrorResponse, request: HttpRequest<any>) {
        if (err.status === 401) {
            this.authService.refreshToken().subscribe(() => {
                this.httpClient.request(request.clone(request))
                    .subscribe();
            });
            console.log('intercepted');
            console.log(err);
        }
    }

    private getAuthorizedRequest(request: HttpRequest<any>): HttpRequest<any> {

        return request.clone({
            headers: request.headers.append('Authorization', this.authService.getAuthTokenString())
        });
    }
}
```

**Comment by rubenCodeforges** [comment]
@moasakthi also i would suggest you take a look at this doc https://developers.google.com/identity/sign-in/web/server-side-flow

**Comment by rubenCodeforges** [comment]
@moasakthi did it helped ?
