### ISSUE TITLE
Change detection after auth iframe

### ISSUE THREAD

**Issue by vitto-moz** [rubenCodeforges/ng-gapi#47]
after auth iframe appears - component loses control of change detection.
Changes can be applied only through changeDetector

I use NgRx so my code for authorization is next (NgRx Effects):
  ```
@Effect()
  tryLogin = this.actions$
    .ofType(AuthActionTypes.TRY_LOGIN)
    .switchMap(() => this.signIn())
    .switchMap(result => of(result ? new LoginSuccess() : new LoginFailure()))

  @Effect()
  loginSuccess = this.actions$
    .ofType(AuthActionTypes.LOGIN_SUCCESS)
    .switchMap((): Observable<RouterActionType> => of(new RouterActions.Go({path: ['/calendar']})))

  private signIn(): Observable<boolean> {
    return this.googleAuth.getAuth()
      .switchMap(auth => {
        return fromPromise(auth.signIn())
      })
      .map((res: GoogleUser) => {
        this.signInSuccessHandler(res)
        return true
      })
      .catch( (err) => {
        console.error('ERROR: ', err);
        return of(false)
      })
  }

  private signInSuccessHandler(res: GoogleUser) {
    this.user = res;
    sessionStorage.setItem(
      this.SESSION_STORAGE_KEY, res.getAuthResponse().access_token
    );
  }
```
How sholuld I use library to avoid this behavior, thanks!

**Comment by rubenCodeforges** [comment]
i think you need ngZone https://dzone.com/articles/understanding-ngzone

**Comment by vitto-moz** [comment]
wrap some code in `this.zone.run(() => res.callback())` made changes - but still have issue
what should I wrap in case on auth2...?
It seems here is enough of zone.run =)

```
 private signIn(): Observable<boolean> {
    return this.zone.run(() => this.googleAuth.getAuth()
      .switchMap(auth => {
        return fromPromise(
          this.zone.run(() => auth.signIn())
        )
      })
      .map((res: GoogleUser) => {
        this.zone.run(() => this.signInSuccessHandler(res))
        return true
      })
```

**Comment by rubenCodeforges** [comment]
@vitto-moz maybe my example project can help you out , this is the userService from it https://github.com/rubenCodeforges/ng-gapi/blob/feature/example-project/examples/src/app/common/user/UserService.ts

**Comment by rubenCodeforges** [comment]
@vitto-moz since you didnt response , i assume it helped , im closing this

**Comment by vitto-moz** [comment]
@rubenCodeforges yes, your hint was helpful, thanks. 
Want to add for those who use NgRx in their projects 
there is a helpful method for returning to Angular Zone 
here is a link to the comment I wrote 
[](https://github.com/angular/zone.js/issues/830#issuecomment-374706995)

**Comment by rubenCodeforges** [comment]
@vitto-moz nice one , thanks !

**Comment by vitto-moz** [comment]
Hi, @rubenCodeforges , once again :)
I want to reveal situation with losing angularZone context in our local meetUp, but I don't understand the entire situation - why it happens :( 
Please, if you have any idea, share them with me. Thanks!

**Comment by rubenCodeforges** [comment]
@vitto-moz hey , mmm its hard to tell for sure .
How about to schedule a meet(hangout) ?

**Comment by vitto-moz** [comment]
@rubenCodeforges, ok, great, what time do you prefer, which timezone?
here is my mail 
v.mozharovsky@gmail.com

**Comment by rubenCodeforges** [comment]
@vitto-moz im in GMT+2 do you have telegram ?

**Comment by vitto-moz** [comment]
yep, I have an account. how to share it with you, by phone number?

**Comment by rubenCodeforges** [comment]
@vitto-moz ill send you my number by email
