### ISSUE TITLE
Connect to Google App Engine Endpoints

### ISSUE THREAD

**Issue by AngelLuisSanchez** [rubenCodeforges/ng-gapi#49]
Hi men!

First of all, thanks for this awesome Gapi service.

I need to consume some GAE (Google App Engine) functions. I deployed my backend into Google project, but I don't know how to connect it.

This is my simple example (without security or any checks):

```
@Api(name = "example", version = "v1", description = "API Endpoint")

public class MiApi {


	@ApiMethod(name = "hello", path = "hello", httpMethod = HttpMethod.POST)

	public Mensaje hello(@Named("n") String name) {
		return new Mensaje();
	}
}
```

How can I call this API mehod from Angular with ng-gapi?

Thanks!

**Comment by rubenCodeforges** [comment]
@AngelLuisSanchez hi , thank you for the response.
A quick answer , you could try and add this typings https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gapi.client.appengine

There is also a readme inside that repo , it shows some examples.
Use ng-gapi to load gapi as show in my examples and in the [demo]( https://ng-gapi-example.stackblitz.io/)

**Comment by AngelLuisSanchez** [comment]
Thanks for your response!

I'll try it, but not seems that this is a solution if I want to use [OAuth 2.0](https://cloud.google.com/endpoints/docs/frameworks/java/authenticating-users#authenticating_with_google_accounts) to connect GAE Endpoints..

Any idea to reach it?

**Comment by rubenCodeforges** [comment]
For OAauth 2.0 you need a token , use ng-gapi to get it , then add it to your header.
See the UserService in the this example https://stackblitz.com/edit/ng-gapi-example

**Comment by AngelLuisSanchez** [comment]
Thanks a lot!

It's running for me. Now I'm sending requests with user (oauth token) and parameters to my security back-end.

I got it!
