### ISSUE TITLE
How can I integrate google drive picker with ng-gapi?

### ISSUE THREAD

**Issue by AngelLuisSanchez** [rubenCodeforges/ng-gapi#50]
Hello again!

Now I'm trying integrate your "ng-gapi library" with google-drive-picker. All of examples that I've founded are about AngularJS or simple JavaScript.

Is it possible to integrate google drive picker with ng-gapi?
How can I load google-drive-picker?

**Comment by rubenCodeforges** [comment]
@AngelLuisSanchez Hi , try to use this typings https://www.npmjs.com/package/@types/google.picker
and then like in my example , use gapi service: 

```TypeScript
export class FooService {
    constructor(gapiService: GoogleApiService) {
        gapiService.onLoad().subscribe(()=> {
           // Here we can use gapi
           gapi.load('picker', onPickerApiLoad);
        });
    }
}
```

See the example from the docs what you can do with `picker` https://developers.google.com/picker/docs/

**Comment by AngelLuisSanchez** [comment]
Ok... At this point, I have object google.picker. Like this:

```
const drivePicker = new google.picker
                                        .PickerBuilder()
                                        .addView(google.picker.ViewId.DOCS)
                                        .setOAuthToken(UserService.SESSION_STORAGE_KEY)
                                        .setDeveloperKey(API KEY)
                                        .enableFeature(google.picker.Feature.NAV_HIDDEN)
                                        .enableFeature(google.picker.Feature.MULTISELECT_ENABLED)
                                        .addView(new google.picker.DocsUploadView())
                                        .build();
drivePicker.setVisible(true);
```

But when I executed this portion of code, it shows this problem:

`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://docs.google.com') does not match the recipient window's origin ('http://localhost:4200').`

I've check my developer key and authorized http://localhost:4200, but it still doesn't work :/

Any idea?

**Comment by AngelLuisSanchez** [comment]
Yeah, you're right!

I enabled Google Drive API (wrong thinking), I was not enabled GOOGLE PICKER API... 

So, It's fix.

**Comment by rubenCodeforges** [comment]
@AngelLuisSanchez great , glad youve made it !
