### ISSUE TITLE
Manage session when token expired

### ISSUE THREAD

**Issue by AngelLuisSanchez** [rubenCodeforges/ng-gapi#51]
Hi men!

I've a problem when the user session expires, also I can't call endpoint functions with this token.

What is the best way to handle it?

**Comment by rubenCodeforges** [comment]
@AngelLuisSanchez hi , i think you just need to refresh the token.

If you are calling a signIn method , it should return you a Promise<GoogleUser> .
now if we check this type https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gapi.auth2/index.d.ts#L232

You can see it has a method `reloadAuthResponse()` which should refresh your token

**Comment by AngelLuisSanchez** [comment]
Ok, I'll try... but, another question in order to manage session, when I entry in the app and do login.

What's up with object GoogleUser?

**Comment by rubenCodeforges** [comment]
Im not getting your question ?

Im just trying to guess what you are trying to do , i assume you want to keep track of your 403 requests and do a refresh of the token.

Perhaps this articles will help you out: 
1. Angular interceptors https://medium.com/@ryanchenkie_40935/angular-authentication-using-the-http-client-and-http-interceptors-2f9d1540eb8
2. Gapi FAQ Refresh token https://developers.google.com/api-client-library/javascript/help/faq#how-do-i-refresh-the-auth-token-and-how-often-should-i-do--------it

**Comment by rubenCodeforges** [comment]
Oh and my examples are just general examples , they should not be taken as solutions , each app is differently

**Comment by AngelLuisSanchez** [comment]
Sorry for my poor explanation...

I got it with handler error in the subscribe.

```
this._apiService.METHOD(this._userService.getToken())
      .subscribe(
        resp => {
        },
        error => {
          // SERVICE THAT HANDLER ERROR (such as token expired)
          this._handlerErrorService.handlerError(error);
        }
      );
  }
```
Thanks a lot for your response!
