### ISSUE TITLE
Using Google email api for sending emails.

### ISSUE THREAD

**Issue by ratnam99** [rubenCodeforges/ng-gapi#55]
Hi, 
This repository seems very helpful to me, just I had a question for you guys. 
Can we use this `ng-gapi` package, for sending system generated emails via web app?
If yes, then please tell me how to implement it. (A basic KT would also do)
Hope to hear from you guys soon.

Thanks in advance.

**Comment by rubenCodeforges** [comment]
@ratnam99 hi . ng-gapi allows you to use google api , here is a doc from google api https://developers.google.com/gmail/api/v1/reference/users/messages/send

**Comment by rubenCodeforges** [comment]
google api uses oAuth , in order to use its resources you need a auth token , there are different ways to get it , with backend or with client, on client you can have a popup or redirect url .
this can be setup in clientCofig:
```
 /**
     * The UX mode to use for the sign-in flow.
     * By default, it will open the consent flow in a popup.
     */
    ux_mode?: "popup" | "redirect";

    /**
     * If using ux_mode='redirect', this parameter allows you to override the default redirect_uri that will be used at the end of the consent flow.
     * The default redirect_uri is the current URL stripped of query parameters and hash fragment.
     */
    redirect_uri?: string;
```
See the Readme for all parameters.
also check out gapi docs , as it is the core of ng-gapi

**Comment by rubenCodeforges** [comment]
@ratnam99 im closing this , seems to be solved

**Comment by ratnam99** [comment]
Yes, Thanks for the help :)

**Comment by rachittyagi** [comment]
Hi @rubenCodeforges 

I am trying to send email from the angular application, but I am struck at one point and the error message I am getting reads "Recipient address required". Can you please help me out in this? (Screenshot attached for reference)
Below are the permissions I am using:

1. https://mail.google.com/
2. https://www.googleapis.com/auth/gmail.readonly

Any help will be highly appreciated. Thanks in Advance. 

![image](https://user-images.githubusercontent.com/1017613/92797399-aa599980-f3cf-11ea-82ab-89e4d951f579.png)
