### ISSUE TITLE
Broken for Angular 6 (RxJS 6)

### ISSUE THREAD

**Issue by jgololicic** [rubenCodeforges/ng-gapi#56]
After updating to Angular 6 which ships with RxJs 6, ng-gapi is not working any more due to RxJs 6 changes:

ERROR in node_modules/ng-gapi/lib/GoogleApiService.d.ts(1,10): error TS2305: Module '"path-to-project/node_modules/rxjs/Observable"' has no exported member 'Observable'.
[1] node_modules/ng-gapi/lib/GoogleAuthService.d.ts(2,10): error TS2305: Module '"path-to-project/node_modules/rxjs/Observable"' has no exported member 'Observable'.
[1] node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

in file GoogleApiService.d.ts at line 1:
`import { Observable } from "rxjs/Observable";`

should become:
`import { Observable } from "rxjs";`

This would then not work anymore on projects using Rxjs below version 6. Is there any plan to update the library or creating new version of it?

**Comment by jgololicic** [comment]
Thank you for fast response! Appreciated!

Should the NPM repository (https://www.npmjs.com/package/ng-gapi) be updated automatically? There is still version 0.0.50 (latest)

**Comment by jgololicic** [comment]
NPM repo is updated! Thank you! Works as expected now!

**Comment by rubenCodeforges** [comment]
@jgololicic thank you for reporting this , i would forgot to update without you.

resolved in https://github.com/rubenCodeforges/ng-gapi/releases/tag/ng-gapi-0.0.51
