### ISSUE TITLE
Account domain does not match hosted_domain specified by gapi.auth2.init.

### ISSUE THREAD

**Issue by GarfID** [rubenCodeforges/ng-gapi#60]
When attempting to log in via google account that has been allready signed in the app causes an error stating ""Account domain does not match hosted_domain specified by gapi.auth2.init." even so the hosted_domain variable in gapiClientConfig has been configured correctly. 
![image](https://user-images.githubusercontent.com/12690205/43770665-b6b6ee16-9a45-11e8-89f0-5d49bb4c5ec6.png)
![image](https://user-images.githubusercontent.com/12690205/43770709-d0e68c60-9a45-11e8-89d7-d3d53a5897bd.png)

**Comment by GarfID** [comment]
@rubenCodeforges Yes, furthermore - new user authorisation (or after logout) doesn't causes any error. Only secondary, "allready logged in" attemts, when the popup ifame gives a straight redirect.

**Comment by GarfID** [comment]
https://stackblitz.com/edit/angular-jwwzcr

You can exam example code here.

**Comment by rubenCodeforges** [comment]
i will check it but why login with authenticated user ?

**Comment by rubenCodeforges** [comment]
I mean you should just refresh the token there was a issue about that, let me find it

**Comment by rubenCodeforges** [comment]
Here was a long story about auth https://github.com/rubenCodeforges/ng-gapi/issues/57

**Comment by rubenCodeforges** [comment]
@GarfID  Посмотрел твой код )))
пиши в телегу если что @codeforges
