### ISSUE TITLE
Auth popUp is not open when calling this.googleAuth.getAuth()

### ISSUE THREAD

**Issue by edward2990** [rubenCodeforges/ng-gapi#61]
here is the package.json just in case is an issue with some versions 

{
  "name": "egret",
  "version": "6.0.0",
  "license": "https://themeforest.net/licenses/terms/regular",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "serveProd": "ng serve --environment=prod",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "5.2.0",
    "@angular/cdk": "5.2.0",
    "@angular/common": "5.2.0",
    "@angular/compiler": "5.2.0",
    "@angular/core": "5.2.0",
    "@angular/flex-layout": "2.0.0-beta.10",
    "@angular/forms": "5.2.0",
    "@angular/http": "5.2.0",
    "@angular/material": "5.2.0",
    "@angular/platform-browser": "5.2.0",
    "@angular/platform-browser-dynamic": "5.2.0",
    "@angular/router": "5.2.0",
    "@swimlane/ngx-datatable": "11.1.7",
    "angular-tag-cloud-module": "^3.0.0",
    "angularfire2": "^5.0.0-rc.11",
    "angularx-social-login": "^1.1.8",
    "chart.js": "2.5.0",
    "classlist.js": "1.1.20150312",
    "core-js": "2.4.1",
    "date-fns": "1.28.5",
    "firebase": "^5.3.0",
    "hammerjs": "2.0.8",
    "ng-gapi": "0.0.51",
    "ng2-charts": "1.6.0",
    "ng2-file-upload": "1.2.1",
    "ng2-translate": "5.0.0",
    "ng2-validation": "4.2.0",
    "ngx-webstorage": "^2.0.1",
    "perfect-scrollbar": "1.3.0",
    "recordrtc": "^5.4.6",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",
    "wavesurfer.js": "^2.0.5",
    "web-animations-js": "2.3.1",
    "zone.js": "0.8.20"
  },
  "devDependencies": {
    "@angular-devkit/core": "0.3.1",
    "@angular/cli": "^1.6.8",
    "@angular/compiler-cli": "5.2.0",
    "@angular/language-service": "5.2.0",
    "copy-webpack-plugin": "4.3.0",
    "@types/hopscotch": "0.2.28",
    "@types/jasmine": "2.5.38",
    "@types/node": "6.0.60",
    "codelyzer": "~2.0.0",
    "enhanced-resolve": "3.3.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "~0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "~0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "2.0.0",
    "tslint": "4.5.0",
    "typescript": "2.4.2"
  }
}

and here is the code in the **user.service.js**
```
public getToken(): string {
    const token: string = sessionStorage.getItem(UserService.SESSION_STORAGE_KEY);
    if (!token) {
      throw new Error('no token set , authentication required');
    }
    return sessionStorage.getItem(UserService.SESSION_STORAGE_KEY);
  }

  public signIn(): void {
    this.googleAuth.getAuth()
      .subscribe((auth) => {
        auth.signIn().then(res => this.signInSuccessHandler(res));
      });
  }

  private signInSuccessHandler(res: GoogleUser) {
    this.user = res;
    sessionStorage.setItem(
      UserService.SESSION_STORAGE_KEY, res.getAuthResponse().access_token
    );
  }
```
when i call the **signIn()** method from the component the auth popup window never shows up. The browser is not blocking the popup the method isn't doing anything

If you need any other info just ask. 

Thanks

**Comment by rubenCodeforges** [comment]
do you have adblock ?

**Comment by rubenCodeforges** [comment]
`and here is the code in the user.service.js`
 are you sure that its js ?

Because your code snippet is Typescript , it wont work in a js file.

also here is a working demo , see if it opens the popup for you https://stackblitz.com/edit/ng-gapi-example

**Comment by rubenCodeforges** [comment]
good now refresh the example and see in app.component at method `  public signIn() ` 
It calls a user service , if it still works , then you have a working example an you can use it

**Comment by edward2990** [comment]
yes it is still opening, i'll copy your example code and I'll let you know if it is ok.

**Comment by edward2990** [comment]
Still no working. i notice in the network section in the debugger that this error is showing up when calling the signIn method

![screenshot_20180827_114015](https://user-images.githubusercontent.com/18198323/44669493-04a47f00-a9ee-11e8-8a3f-5a21eb83408e.png)

**Comment by rubenCodeforges** [comment]
well that tells me not much , there is a warning in console , what is it ?
And its definitely something with your app setup ( settings ) or maybe google api console settings ?

**Comment by edward2990** [comment]
yes I know. there is not warnings and errors in the console. Do i need to specify any specific config in the google console? i guess i can start checking that first, because the code is the exact one from your working example

**Comment by rubenCodeforges** [comment]
Yes you need to create a app in the console and set it up
read google docs first

**Comment by rubenCodeforges** [comment]
Have you read this https://github.com/rubenCodeforges/ng-gapi#configurations ?

**Comment by edward2990** [comment]
yes i already have a googe app configured in google console and i set up this configurations for the ng-gapi config scopes and discovery_docs are this ones 

SCOPES: 'https://www.googleapis.com/auth/drive.metadata.readonly',
DISCOVERY_DOCS: ['https://www.googleapis.com/discovery/v1/apis/drive/v3/rest']

if there is anything else to configure in google console i think that this part is OK

**Comment by rubenCodeforges** [comment]
@edward2990 i can not debug your app based on a code snippet and couple of screenshots.
But for sure i can say its not the lib that causes the issue and you can confirm this from the demo. it uses all the same code.

If you followed the readme and even copied the demo code ,you should be good.

the only thing i can help you with , is if you make a stackblitz with your code ( not all ) then i could try and debug it.

**Comment by rubenCodeforges** [comment]
Closing  due to inactivity
