### ISSUE TITLE
"Cookies are not enabled in current environment

### ISSUE THREAD

**Issue by elieobeid7** [rubenCodeforges/ng-gapi#64]
Running the demo on chrome I get

```
{
  "error": "idpiframe_initialization_failed",
  "details": "Cookies are not enabled in current environment."
}
```

On firefox I get

`uncaught exception: [object Object]`

It doesn't matter if I'm running on localhost or stackblitz, same error

**Comment by elieobeid7** [comment]
I forgot to say that

- on Chrome I get the error running the demo on localhost and stackblitz
-  on firefox I get the error only on localhost, stackblitz is working
- all i'm doing is running the demo as is, on windows 10, using the latest chrome and latest firefox

Is there anything I could do at all to help you fix it? I need to do google sign in and all other libraries are broken for example [here](https://github.com/abacritt/angularx-social-login/issues/132) and all other plugins are forks of that, so your library is all i have left. I just need to trigger the login, the rest will be handled by google client php sdk

**Comment by rubenCodeforges** [comment]
@elieobeid7 can you paste a screen shot of the console with error ?w

**Comment by elieobeid7** [comment]
It works now, there was some problems with my browser I guess, Thank you.

**Comment by beevekmgr** [comment]
![image](https://user-images.githubusercontent.com/19634148/66012324-6b944180-e4e6-11e9-9557-91d615376a17.png)
Same problem how to solve?

**Comment by rubenCodeforges** [comment]
@beevekmgr doesn't look like it's ng-gapi related

**Comment by beevekmgr** [comment]
> @beevekmgr doesn't look like it's ng-gapi related

Sorry It was related to gapi... but it is solved.. now its because of browser script blocked.. Thank You for your concern

**Comment by aishwary11** [comment]
I'm also facing same issue please help
![cookies](https://user-images.githubusercontent.com/49820149/78995069-30429180-7b5f-11ea-90c4-0eaa8834761b.png)

**Comment by Milanchhatralia** [comment]
> > @beevekmgr doesn't look like it's ng-gapi related
> 
> Sorry It was related to gapi... but it is solved.. now its because of browser script blocked.. Thank You for your concern

Thanks for clearing as it solved my browser problem too

**Comment by simran-anilabsinc** [comment]
> Running the demo on chrome I get
> 
> ```
> {
>   "error": "idpiframe_initialization_failed",
>   "details": "Cookies are not enabled in current environment."
> }
> ```
> 
> On firefox I get
> 
> `uncaught exception: [object Object]`
> 
> It doesn't matter if I'm running on localhost or stackblitz, same error

Solution=>            i was also facing same problem, then i recreate the client id and redirect uri, now it's working fine on another laptop but not on mine, because it's the problem in chrome , so try to update your chrome
Now it's working fine in firefox and other browser for me but not in chrome, so try to another laptop in which has update chrome version, i will work fine there
