### ISSUE TITLE
How to change ClientId from any component ?

### ISSUE THREAD

**Issue by upendrasengarmbwk** [rubenCodeforges/ng-gapi#75]
I can set clientId while initiating module but how can I dynamically change clientId and scopes.

let gapiClientConfig: NgGapiClientConfig = {
    client_id: "CLIENT_ID",
    discoveryDocs: ["https://analyticsreporting.googleapis.com/$discovery/rest?version=v4"],
    scope: [
        "https://www.googleapis.com/auth/analytics.readonly",
        "https://www.googleapis.com/auth/analytics"
    ].join(" ")
};

**Comment by rubenCodeforges** [comment]
it is not supported
