### ISSUE TITLE
DUDE

### ISSUE THREAD

**Issue by ErwinBustillo** [rubenCodeforges/ng-gapi#78]
I'm using angular 7.2 and I want to make logout with this npm package into my angularservice. How can you make it?

**Comment by rubenCodeforges** [comment]
GoogleAuthService.getAuth() returns auth2 observable then you can use
signOut() on it

official docs https://developers.google.com/identity/sign-in/web/reference

**Comment by rubenCodeforges** [comment]
Closed due inactivity
