### ISSUE TITLE
Sign in works but getting Calendar gets error 401

### ISSUE THREAD

**Issue by elenat82** [rubenCodeforges/ng-gapi#79]
Hi, 
I am trying to show the user's Google Calendar in my angular 7 app.

[Here is a stackblitz demonstrating the issue](https://stackblitz.com/edit/angular-rkrgev)

I also checked google developer console and my localhost is whitelisted and I allowed my app to access my calendar data in my google profile.

The problem is that after successful login I want to get list of events from primary calendar of the logged user, but passing the just obtained token as a parameter in the request gets me a 401 error.

Here are relevant files:

calendar.component.ts
`    import { Component, ChangeDetectionStrategy, ViewChild, TemplateRef, OnInit, AfterViewInit, 
   ChangeDetectorRef, NgZone } from '@angular/core';

    import { UserService } from './user.service';
    import { SheetResource } from './sheet-resource';

    import { Subject, Observable } from 'rxjs';

    import { GoogleAuthService } from 'ng-gapi';

    import { GoogleApiService } from 'ng-gapi';

    @Component({
     selector: 'app-calendar',
     templateUrl: './calendar.component.html',
     changeDetection: ChangeDetectionStrategy.OnPush,
    })

    export class CalendarComponent implements OnInit, AfterViewInit {
      user;

       constructor(private userService: UserService, private sheetResource: SheetResource, private 
    gapiService: GoogleApiService, private ngZone: NgZone) {
        this.gapiService.onLoad().subscribe(
           (res) => { console.log("res ->", res) },//true
           (err) => { console.log("err ->", err) }

          );

        }

       ngOnInit() {

       }

       ngAfterViewInit() {

      }

       public isLoggedIn(): boolean {
         return this.userService.isUserSignedIn();
      }

       public signIn() {
         this.userService.signIn().subscribe(

           (auth) => {
             console.log("auth....", auth);
             auth.signIn()
               .then(
                (res) => {
                  this.ngZone.run(() => {
                    this.user = res;
                    sessionStorage.setItem(
                      "CalendarAccessToken", res.getAuthResponse().access_token
                     );
                    this.sheetResource.getCalendars(res.getAuthResponse().access_token)
                      .subscribe(
                        (res) => { console.log(res) },
                        (err) => { console.log(err) }
                      );
                  });
                },
                (err) => this.userService.signInErrorHandler(err));
          },
          (err) => { console.log("err....", err) }
        );
      }

      public signOut() {
        this.userService.signOut();
      }

    }
`

sheet-resource.ts
`    
         import {Injectable} from "@angular/core";
         import {HttpClient, HttpHeaders} from "@angular/common/http";
         import {Observable} from "rxjs/Observable";

      @Injectable()
      export class SheetResource {
        //private readonly API_URL: string = 'https://sheets.googleapis.com/v4/spreadsheets';

        private readonly API_URL: string = 'https://www.googleapis.com/discovery/v1/apis/calendar/v3';

        constructor(private httpClient: HttpClient) {
        }

        // authtoken as parameter only for demo purpose , better use a UserService to get the token
        public findById(spreadsheetId: string, authtoken: string): Observable<any> {
            return this.httpClient.get(this.API_URL + '/' + spreadsheetId, {
            headers: new HttpHeaders({
                    Authorization: `Bearer ${authtoken}`
                })
            });
        }

        public create(authtoken: string): Observable<any> {
            return this.httpClient.post(this.API_URL,{}, {
            headers: new HttpHeaders({
                    Authorization: `Bearer ${authtoken}`
                })
            });
        }

        public getCalendars(authtoken: string) {
            console.log("authtoken ", authtoken);
            return this.httpClient.get('https://www.googleapis.com/calendar/v3/calendars/primary', {
                headers: new HttpHeaders({
                    Authorization: `Bearer ${authtoken}`
                })
            });
        }
    }

`

user.service.ts
`
        import {Injectable, NgZone} from "@angular/core";
        import {GoogleAuthService} from "ng-gapi/lib/GoogleAuthService";
        import GoogleUser = gapi.auth2.GoogleUser;
        import GoogleAuth = gapi.auth2.GoogleAuth;
        import { Observable } from 'rxjs';

      @Injectable()
      export class UserService {
      public static readonly SESSION_STORAGE_KEY: string = "CalendarAccessToken";
        private user: GoogleUser = undefined;

     constructor(private googleAuthService: GoogleAuthService,
        private ngZone: NgZone) { }

        public setUser(user: GoogleUser): void {
        this.user = user;
    }

    public getCurrentUser(): GoogleUser {
        return this.user;
    }

    public getToken(): string {
        let token: string = sessionStorage.getItem(UserService.SESSION_STORAGE_KEY);
        if (!token) {
            throw new Error("no token set , authentication required");
        }
        return sessionStorage.getItem(UserService.SESSION_STORAGE_KEY);
    }

    public signIn() {
        return this.googleAuthService.getAuth()/* .subscribe((auth) => {
        auth.signIn().then(res => this.signInSuccessHandler(res), err => this.signInErrorHandler(err));
    }); */
    }

    //TODO: Rework
    public signOut(): void {
        this.googleAuthService.getAuth().subscribe((auth) => {
            try {
                auth.signOut();
            } catch (e) {
                console.error(e);
            }
            sessionStorage.removeItem(UserService.SESSION_STORAGE_KEY)
        });
    }

    public isUserSignedIn(): boolean {
        return ( sessionStorage.getItem(UserService.SESSION_STORAGE_KEY) != null && sessionStorage.getItem(UserService.SESSION_STORAGE_KEY) != undefined);
    }

    public signInSuccessHandler(res: GoogleUser) {
        this.ngZone.run(() => {
            this.user = res;
            const token = res['Zi'].access_token;
            sessionStorage.setItem(
                UserService.SESSION_STORAGE_KEY, token
            );
        });
    }

    public signInErrorHandler(err) {
        console.warn(err);
    }
    }

`

app.module.ts
`
            import { NgModule } from '@angular/core';
            import { BrowserModule } from '@angular/platform-browser';
            import { FormsModule } from '@angular/forms';
            import { HttpClientModule} from '@angular/common/http';

            import { AppComponent } from './app.component';
            import { HelloComponent } from './hello.component';
            import { CalendarComponent } from './calendar/calendar.component';

            import { UserService } from './calendar/user.service';
            import { GoogleApiModule, GoogleApiService, GoogleAuthService, 
             NgGapiClientConfig, NG_GAPI_CONFIG, GoogleApiConfig } from "ng-gapi";
            import { SheetResource } from './calendar/sheet-resource';

            let gapiClientConfig: NgGapiClientConfig = {
            client_id: "YOUR_CLIENT_ID",
            discoveryDocs: ['https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest'],
            scope: [
                'https://www.googleapis.com/auth/calendar'
            ].join(" ")
            };

            @NgModule({
            imports:      [ BrowserModule, FormsModule, HttpClientModule, GoogleApiModule.forRoot({
                provide: NG_GAPI_CONFIG,
                useValue: gapiClientConfig
                }) ],
            declarations: [ AppComponent, HelloComponent, CalendarComponent ],
            providers: [UserService, SheetResource],
            bootstrap:    [ AppComponent ]
            })
            export class AppModule { }

`

**Comment by rubenCodeforges** [comment]
@elenat82 Hey there , thanks for using our lib.

can you log the exact error that you get when you receive 401 ?
That might give us some insights on what is wrong.

**Comment by elenat82** [comment]
Yes, this is what I see from the network:

here is response tab:

`
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}

`

And here is headers tab:
Request URL: https://www.googleapis.com/calendar/v3/calendars/primary 
Request Method: GET 
Status Code: 401 
Remote Address: 172.217.23.74:443 
Referrer Policy: no-referrer-when-downgrade 
access-control-allow-credentials: true 
access-control-allow-origin: http://localhost:4300 
access-control-expose-headers: Content-Encoding,Content-Length,Content-Type,Date,Server,Vary,WWW-Authenticate,X-Google-GFE-Backend-Request-Cost 
alt-svc: quic=":443"; ma=2592000; v="46,44,43,39" 
cache-control: private, max-age=0 
content-encoding: gzip 
content-length: 162 
content-type: application/json; charset=UTF-8 
date: Thu, 14 Mar 2019 13:43:05 GMT 
expires: Thu, 14 Mar 2019 13:43:05 GMT 
server: GSE
status: 401 
vary: Origin, X-Origin 
www-authenticate: Bearer realm="https://accounts.google.com/", error=invalid_token 
x-content-type-options: nosniff 
x-frame-options: SAMEORIGIN 
x-xss-protection: 1; mode=block 
Provisional headers are shown 
Accept: application/json, text/plain, */* 
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyMiIsImlhdCI6MTU1MjQwMzcyNCwiZXhwIjoxNTUzMDA4NTI0fQ.LhAWC4Zj2Non5mR96P72Tes-IFbmdnCVKi9V-27n_wBLZkci2qcswB3ARHhJRWM-rTJRPdxd5zWIgzknaBb8LQ 
Origin: http://localhost:4300 
Referer: http://localhost:4300/calendar 
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by rubenCodeforges** [comment]
ok from first look , its definitly something wrong with configuration.

I also see in the official docs that there are 2 scopes and you provide just 1 

![image](https://user-images.githubusercontent.com/6032797/54371365-8baf0100-4679-11e9-9b99-ce5e491a43b2.png)
Maybe that is your issue

**Comment by rubenCodeforges** [comment]
And just to be sure in the configs . `YOUR_CLIENT_ID` have you replaced it with yours ?

**Comment by elenat82** [comment]
Thank you Ruben,
the problem was the missing scope!

**Comment by rubenCodeforges** [comment]
@elenat82 glad i could help.
If you could also put a thumb up for my new video tutorials , Building a full-stack app with Angular and NestJs , i would much appreciate it.
https://www.youtube.com/playlist?list=PLq1kZ5GbKd4qyDcK3IHGSi4FDAL6fRZeL
