### ISSUE TITLE
Not working in lazy loading

### ISSUE THREAD

**Issue by KK220794** [rubenCodeforges/ng-gapi#84]
when I try to use lazy loading with this, it is not working.

**Comment by rubenCodeforges** [comment]
any examples ?

**Comment by KK220794** [comment]
I have two modules and I have used google signIn in both the modules.
when I  lazy load both module, Google signIn is working only on the first loaded module. and in the second module there is no response in the google sign in.  whereas without lazy loading,  both the module are running absolutely perfect.

**Comment by faran52000** [comment]
@KK220794 did you get it resolved by any chance?

**Comment by rubenCodeforges** [comment]
related to #46
