### ISSUE TITLE
How to get access of the gapi script and load client library

### ISSUE THREAD

**Issue by ksuhiyp** [rubenCodeforges/ng-gapi#86]
I have successfully made to get the access token through the Auth Service.
Now I have the following questions:

I am trying to make requests to the people API ,how to load the client library to  the gapi instance --which is loaded from the, `this.googleService.onLoad().subscribe()`-- 
Here is an example:
```
private signInSuccessHandler(res: gapi.auth2.GoogleUser) {
    const userData = gapi.client.people.people.get({ personFields: 'addresses emailAddresses names phoneNumbers photos', resourceName: 'people/me' });
    console.log(userData)

  }
```
gapi.client.people throws and error of: cannot get people of undefined, so far the gapi instance has the following structure:
```
_:Object {b: , _DumpException: , aa: Array(36), …}
auth2:Object {init: , authorize: , _gt: , …}
config:Object {get: , update: }
load:function(a,b){ … }
loaded_0:null
loaded_1:function(u){ … }
```

**Comment by rubenCodeforges** [comment]
@ksuhiyp in your example you call gapi, i dont see where you got it ?
i mean `signInSuccessHandler` get `res` as a parameter witch is `GoogleUser` 
there is no `gapi` in your example.

If you do want the gapi instance , you have to use `gapiService: GoogleApiService` as in the example https://github.com/rubenCodeforges/ng-gapi#example

```typescript

export class FooService {
    constructor(gapiService: GoogleApiService) {
        gapiService.onLoad().subscribe(()=> {
           // Here we can use gapi for example
           gapi.client.people.people.get()
           
        });
    }
}
```
