### ISSUE TITLE
CORS issue on making api request with the token.

### ISSUE THREAD

**Issue by SabirHossain** [rubenCodeforges/ng-gapi#88]
I'm trying to get user contacts from google api and I'm using ng-gapi for signing in the user and get the access_token, but when I make call for the contact list I get 404 and the CORS error

> Access to XMLHttpRequest at 'https://people.googleapis.com/v1/me/connections' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Setting the token for user
```
const copiedReq = req.clone({

      setHeaders: {
          'Authorization': `Bearer $(my_token)`,  
        }
  });
return next.handle(copiedReq);
```
The http call

```
GetGoogleContacts(): Observable<any> {
        return this.httpClient.get<any>(`https://people.googleapis.com/v1/me/connections`);
    }
```

**Comment by rubenCodeforges** [comment]
How do you get 'my_token' ?

**Comment by rubenCodeforges** [comment]
Did you also configured the URL of your app in the Google admin console ?
You have to whitelist the URL from where your app will talk to gapi

**Comment by SabirHossain** [comment]
@rubenCodeforges 
I'm getting the token from sessionStorage, and yes the url http:\\localhost:4200 is white-listed in the app console

**Comment by rubenCodeforges** [comment]
The cord usually means a misconfiguration of the app in Google Dev console, please double check it.

**Comment by SabirHossain** [comment]
I had to use gapi for getting the contacts, perhaps google doesn't support direct api call. better you add some method in 'ng-gapi' to make those calls and get data. Thank you.

**Comment by rubenCodeforges** [comment]
Google supports direct API calls and you use gapi to get the auth token.

From your comments I can't tell much, there is no configuration, no example how and when you store your token.
