### ISSUE TITLE
Increase Expiry time 

### ISSUE THREAD

**Issue by vignesh007vicky** [rubenCodeforges/ng-gapi#89]
how to increase expiry time in this plugin

its taking default 3600 seconds

let gapiClientConfig: NgGapiClientConfig = {
  client_id: (AppSettings.isprodMode == true ? AppSettings.prod_clientId : AppSettings.dev_clientId),
  discoveryDocs: ["https://analyticsreporting.googleapis.com/$discovery/rest?version=v4"],
  scope: [
    "https://www.googleapis.com/auth/cloud_search.query"
  ].join(" ")
};

**Comment by rubenCodeforges** [comment]
@vignesh007vicky Due to security reasons, you cannot change the duration of the access token's expiry. However, you can refresh an access token without prompting the user for permission if you requested offline access to the scopes associated with the token.

**Comment by seavor** [comment]
Hey @rubenCodeforges. Reading through the documentation, it doesn't actually seem like refresh tokens (offline status) can be granted to web applications.

Is there a way to pass a server-side generated auth URL into the popup auth flow, instead of initializing client side auth?

If not, would it be something you think you'd be able to provide?

**Comment by rubenCodeforges** [comment]
@seavor Hi , sorry for late response , i was on a 4 day holiday :)
Basically the ng-gapi is a angular wrapper for gapi, if you want to generate server side the token you basically do not need ng-gapi/gapi , simply use the REST API resources from google.

For your client side just create a request interceptor and provide the required headers.

Example auth intereceptor.

```typescript
@Injectable({
    providedIn: 'root'
})
export class AuthInterceptorService implements HttpInterceptor {
    constructor(private authService: AuthService,
                private snack: MatSnackBar,
                private dialog: MatDialog,
                private router: Router) {
    }

    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        // BYPASS ASSETS REQUESTS
        if (this.isAssetsRequest(req)) {
            return next.handle(req);
        }
        let authorizedRequest;
        if (this.authService.getToken()) {
            authorizedRequest = req.clone({
                headers: req.headers.set(
                    'Authorization',
                    `Bearer TOKEN`
                )
            });

        }
        return next.handle(authorizedRequest || req)
            .pipe(
                catchError((err: any) => {
                    if (err instanceof HttpErrorResponse) {
                        if (err.status === 401) {
                            // DO SOMETHING MAYBE THROW ERROR

                        }
                        if (err.status === 403) {
                            // DO SOMETHING MAYBE THROW ERROR
                        }
                        return throwError(err);
                    } else {
                        return throwError(err);
                    }
                })
            );
    }
    
    private isAssetsRequest(req: HttpRequest<any>) {
        return _.includes(req.url, 'assets') || _.includes(req.url, 'Module');
    }
}
```
