### ISSUE TITLE
undefined disocveryDocs

### ISSUE THREAD

**Issue by samwootton** [rubenCodeforges/ng-gapi#91]
Hi,

Looking at src I don't see how discoveryDocs would be available:

```
constructor(@Inject(NG_GAPI_CONFIG) config: NgGapiClientConfig) {
        this.config = new GoogleApiConfig(config);
        this.loadGapi().subscribe();
    }
```

GoogleApiConfig doesn't have a discoveryDocs property, yet this is what you're setting it to.  When i attempt to access discoveryDocs I get undefined.

```
var gapiConfig:GoogleApiConfig = this.gapi.getConfig();
var ngapiConfig:NgGapiClientConfig = gapiConfig.getClientConfig();
// ngapiConfig.discoveryDocs
```

Thanks, Sam

**Comment by rubenCodeforges** [comment]
@samwootton hi , look at https://github.com/rubenCodeforges/ng-gapi/blob/master/src/config/GoogleApiConfig.ts#L4

the interface extends configs and adds discovery docs

**Comment by rubenCodeforges** [comment]
its probably undefined because you did not provided the config in the forRoot, see example https://github.com/rubenCodeforges/ng-gapi#example

**Comment by samwootton** [comment]
Thanks, I did, just didn't post it (in order to keep post short):

```
const gapiClientConfig: NgGapiClientConfig = {
  client_id: "xxx.apps.googleusercontent.com",
  discoveryDocs: ["https://www.googleapis.com/discovery/v1/apis/youtube/v3/rest"],
  scope: "https://www.googleapis.com/auth/youtube.force-ssl"
  };

@NgModule({
  declarations: [
    AppComponent,
    PlayListComponent,
    VideoItemComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    MatListModule ,
    HttpClientModule,
    GoogleApiModule.forRoot({
      provide: NG_GAPI_CONFIG,
      useValue: gapiClientConfig
      })
  ],
```

**Comment by rubenCodeforges** [comment]
how do you get `var gapiConfig:GoogleApiConfig = this.gapi.getConfig();`  ?
where is `this.gapi` coming from ?

**Comment by samwootton** [comment]
In my services:
```
constructor(
    private gapi: GoogleApiService,
    private googleAuth: GoogleAuthService,
    private httpClient: HttpClient
  ) {

    gapi.onLoad().subscribe(()=> {
      googleAuth.getAuth().subscribe((auth) => {
        auth.signIn().then(res => this.signInSuccessHandler(res),
        err => this.signInErrorHandler(err));
      })
    })
  }
```
And
```
signInSuccessHandler(user:gapi.auth2.GoogleUser){
    
    this.user = user;
    var userName:string = this.user.getBasicProfile().getGivenName();

    var authResponse:gapi.auth2.AuthResponse = user.getAuthResponse();
    var accessToken:string = authResponse.access_token;
    
    var gapiConfig:GoogleApiConfig = this.gapi.getConfig();
}
```

**Comment by rubenCodeforges** [comment]
try to use in `onLoad`

```typescript
signInSuccessHandler(user:gapi.auth2.GoogleUser){
    this.gapi.onLoad().subscribe(() =>{
       this.user = user;
       const userName:string = this.user.getBasicProfile().getGivenName();
       const authResponse:gapi.auth2.AuthResponse = user.getAuthResponse();
       const accessToken:string = authResponse.access_token;
       const gapiConfig:GoogleApiConfig = this.gapi.getConfig();
    });
}

```

**Comment by samwootton** [comment]
Thanks, and apologies, but confused here, where are you signing in and where do you get user reference from?

**Comment by samwootton** [comment]
Thanks, but I'm confused here, and discovery docs is still undefined and why would I listen to onLoad twice?

**Comment by rubenCodeforges** [comment]
Then something is wrong with the setup , in fact why do you need discovery docs ?

`onLoad` is a lifecycle hook , it is fired when `gapi` lib is loaded to make sure you have gapi available

**Comment by samwootton** [comment]
Thank you for your help.

I use discoveryDocs so I can get the youtube client API (which I was having trouble referencing):

> The discoveryDocs field identifies a list of API Discovery documents that your application uses. A Discovery document describes the surface of an API, including its resource schemas, and the JavaScript client library uses that information to generate methods that applications can use. In this example, the code retrieves the discovery document for version 3 of the YouTube Data AP

In a plain JS app I used to have:
```
loadClient() {
    this.showOutput1("loadClient() gapi.client load");
      return gapi.client.load(this.DISCOVERY_DOCS)
          .then( () => {
            this.showOutput1("GAPI client loaded for API");
            this.getVideoCategories();
          },
          function(err) { console.error("Error loading GAPI client for API", err); });
  }
```

And reference:
```
gapi.client.youtube.playlists.list({
      part: 'snippet',
      mine: true,
      prettyPrint: true
    }).then((response) => {}
```

**Comment by rubenCodeforges** [comment]
wait but you dont need to do this , because ng-gapi is loading this for you

**Comment by rubenCodeforges** [comment]
@samwootton 

```Typescript

export class FooService {
    constructor(gapiService: GoogleApiService) {
        gapiService.onLoad().subscribe(()=> {
           // Here we can use gapi
           gapi.client.youtube.playlists.list({
      part: 'snippet',
      mine: true,
      prettyPrint: true
    }).then((response) => {}
        });
    }
}
```

**Comment by samwootton** [comment]
Thanks. But I can't see "client". Below is "_Property 'client' does not exist on type 'GoogleApiService_"

`console.log(this.gapi.client);`

So my first step was to get rid of obvious errors, such as discovery docs being undefined. My package.json has:

"ng-gapi": "0.0.73"

My imports are:

```
 imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    HttpClientModule,
    GoogleApiModule.forRoot({
      provide: NG_GAPI_CONFIG,
      useValue: gapiClientConfig
      })
  ]
```

But I don't see an example of "client" being accessed in your docs. I don't seem to be able to see discoveryDocs.  Do you have an example on ng-gapi at all?

Thanks, Sam

**Comment by rubenCodeforges** [comment]
How about the demo in the docs ?
https://github.com/rubenCodeforges/ng-gapi#usage

**Comment by rubenCodeforges** [comment]
console.log(this.gapi.client)

**Comment by samwootton** [comment]
Okay, thanks for your continued help, but clearly I'm confused here. All I'm trying to do is replicate what I had in my non ng-api version of my app i.e. where I could just do:
```
  loadClient() {
      return gapi.client.load(this.DISCOVERY_DOCS)
          .then( () => {
            this.getVideoCategories();
          },
          function(err) { console.error("Error loading GAPI client for API", err); });
  }
```
I could use this anywhere in my class, no problem. I could just reference "gapi.client" and use it e.g.
```
getPlaylists() {
    gapi.client.youtube.playlists.list({}...);
}
```
I don't seem to be able to do this using ng-api, even if I have it in onLoad.  The example you reference doesn't have code that just uses gap outside of onLoad, even for that matter, an example of just simply calling a function of gapi.

Thanks, Sam

**Comment by rubenCodeforges** [comment]
@samwootton well look at this example https://github.com/rubenCodeforges/ng-gapi/blob/master/src/GoogleAuthService.ts#L27 

Also make sure you call onLoad in a AppComponent on init or App Initialize

**Comment by samwootton** [comment]
Hi @rubenCodeforges thanks for your help.
However, I've decided to not use an extra library, and instead just load gapi directly,
Thanks again, Sam
