### ISSUE TITLE
Can I access google drive api using ng-gapi ?

### ISSUE THREAD

**Issue by Alec-Aldrine-Lakra** [rubenCodeforges/ng-gapi#92]

**Comment by rubenCodeforges** [comment]
Yes you can , just use ng-gapi to generate a token and simply use the google drive apihttps://developers.google.com/drive/api/v3/about-sdk

**Comment by Alec-Aldrine-Lakra** [comment]
I am able to generate the token after authenticating but then what is the next step to access the user's drive ?

**Comment by rubenCodeforges** [comment]
```js
const instance  = gapi.auth2.getAuthInstance()
authInstance.grantOfflineAccess() // returns promise with code - the token
```

**Comment by rubenCodeforges** [comment]
Inactivity
