### ISSUE TITLE
npm version 0.0.90 is empty

### ISSUE THREAD

**Issue by runette** [rubenCodeforges/ng-gapi#98]
Thank you for releasing the update.

Unfortunately - the npm package for version 0.0.90 is effectively empty - only the config files.

**Comment by godbit** [comment]
Im having the same issue.

**Comment by darroyos** [comment]
Hope gets fixed soon. Thanks for updating and maintaining this library

**Comment by rubenCodeforges** [comment]
@godbit @darroyos @runette npm 0.0.91 published

**Comment by godbit** [comment]
Thank you! :)
